### ISSUE TITLE
Make pluralization systematic

### ISSUE THREAD

**Issue by mdejean** [sharkdp/purescript-quantities#29]
Some units are missing their plural forms, for example Farad

    10 × microfarads × 10 kΩ  
    Unknown identifier: microfarads

It would probably be better rather than adding plural forms and abbreviations as synonyms to have a more systematic approach.

Most units are regular nouns: 1 farad -> 2 farads. Some are irregular: 1 henry -> 2 henries. Some have no plural: 1 hertz -> 2 hertz.

**Comment by sharkdp** [comment]
Thank you very much for the feedback!

Do you have any proposals on how this could be treated in a systematic way? I'm afraid all plural forms will simply have to be listed somewhere. You are right though, it should be done in a more consistent way (probably here in this repository where we basically "store" the units).
