### ISSUE TITLE
"per" should have higher precedence than /

### ISSUE THREAD

**Issue by mdejean** [sharkdp/purescript-quantities#30]
```
≫ 3 USD per gallon / 10 miles per gallon * 500 miles  
   (((3 USD / gal) / 10 mi) / gal) × 500 mi  
   = 150 USD/gal²
```

1 / mile per gallon is interpeted as (1/mile) per gallon. Much like implicit multiplication, "per" should have higher precedence than explicit division.

**Comment by sharkdp** [comment]
Thank you for your feedback!

Could you please transfer this ticket to the [Insect repository](https://github.com/sharkdp/insect)?

purescript-quantities is only the underlying library for handling physical units.
