### ISSUE TITLE
Use Gregorian year instead of Julian one?

### ISSUE THREAD

**Issue by triallax** [sharkdp/purescript-quantities#51]
Seeing 92feca4ec665d129d40aa31dbd70da34414cb483, I'm a bit puzzled as to why the Julian year was used, and not the Gregorian one, which is both much more widespread (https://en.wikipedia.org/wiki/Adoption_of_the_Gregorian_calendar#Present_situation) and more accurate. Is there a reason for that?

Naturally, if the year were to be changed, the month should be too.

Alternatives I considered:

- maybe we can have a `julianyear` or something like that, and change `year` to be a Gregorian year (or vice versa)?

**Comment by triallax** [comment]
Hmm, just found https://github.com/sharkdp/purescript-quantities/issues/15#issuecomment-511130547. Is the fact that the light year is defined in terms of the Julian year enough of a reason to stick to it?

**Comment by sharkdp** [comment]
I think I wasn't aware of all subtleties until I read about them now. I like the idea of changing the definition of `year` once more to the Gregorian year.

Adding `julianyear` also sounds like a great idea! That solves the "problem" with `lightyear` :+1:

**Comment by sharkdp** [comment]
Let's make sure to mark this as a breaking change
