### ISSUE TITLE
Add the Faraday constant

### ISSUE THREAD

**Issue by triallax** [sharkdp/purescript-quantities#60]
https://en.wikipedia.org/wiki/Faraday_constant

**Comment by sharkdp** [comment]
Sounds good

**Comment by triallax** [comment]
The symbol for the Faraday constant is F, but that conflicts with the symbol for farads. What name do you think we should use for the constant?

Somewhat related is the uncommon unit of charge called "[faraday](https://en.wikipedia.org/wiki/Faraday_constant#Faraday_%E2%80%93_a_unit_of_charge)." I think it would be nice to add, what do you think?

**Comment by sharkdp** [comment]
Let's just call it `faraday_constant`? I don't think we need a short name for it, certainly not in purescript-quantities.

**Comment by triallax** [comment]
Certainly not, I was thinking about Insect there.
