### ISSUE TITLE
New units: molar and molal

### ISSUE THREAD

**Issue by triallax** [sharkdp/purescript-quantities#61]
[molar](https://en.wikipedia.org/wiki/Molar_(unit)#Units) = mol/L and [molal](https://en.wikipedia.org/wiki/Molality#Unit) = mol/kg. Their respective symbols are M and m, but they conflict with the symbols for nautical mile and meter, so I suppose we'll have to add only the full names.

**Comment by sharkdp** [comment]
Sounds good!

> Their respective symbols are M and m, but they conflict with the symbols for nautical mile and meter, so I suppose we'll have to add only the full names.

:+1:
